### PR TITLE
fix: support gatsby base dirs outside the site root

### LINKED ISSUE #271: Plugin does not work for monorepo
# Description

There is a [Gatsby Kontent packages monorepo](https://github.com/Kentico/kontent-gatsby-packages) containing a development site + a couple of examples. As a part of https://github.com/Kentico/kontent-gatsby-packages/issues/202 I wanted to use this plugin instead deprecated Gatsby Cache plugin.

**Steps to reproduce**

* Fork the repository
* Register the repo to Netlify with its config (you can substitute `dsg-ssr`, with `navigation`/`relationships`/`resolution`)
    * Build command `yarn build:dsg-ssr`
    * Publish directory `/examples/dsg-ssr/public`
* Install this plugin

The build failed on (error from example `dsg-ssr`, but the same if on all examples):

```
12:07:02 PM: ────────────────────────────────────────────────────────────────
12:07:02 PM:   Dependencies installation error                               
12:07:02 PM: ────────────────────────────────────────────────────────────────
12:07:02 PM: ​
12:07:02 PM:   Error message
12:07:02 PM:   A Netlify Function failed to require one of its dependencies.
12:07:02 PM:   Please make sure it is present in the site's top-level "package.json".
​
12:07:02 PM:   In file "/opt/build/repo/.netlify/functions-internal/__api/__api.js"
12:07:02 PM:   Cannot find module '../../../.cache/functions/manifest.json' from '/opt/build/repo/.netlify/functions-internal/__api'
12:07:02 PM: ​
12:07:02 PM:   Resolved config
12:07:02 PM:   build:
12:07:02 PM:     command: yarn build:dsg-ssr
12:07:02 PM:     commandOrigin: ui
12:07:02 PM:     environment:
12:07:02 PM:       - NODE_VERSION
12:07:02 PM:     publish: /opt/build/repo/examples/dsg-ssr/public
12:07:02 PM:     publishOrigin: ui
12:07:02 PM:   functions:
12:07:02 PM:     __api:
12:07:02 PM:       external_node_modules:
12:07:02 PM:         - msgpackr-extract
12:07:02 PM:       included_files:
12:07:02 PM:         - examples/dsg-ssr/.cache/functions/**
```

**Expected behavior**

Build does not fail and DSG and SSG work.

**Environment**

I might be able to share the netlify project, if you need.

### PR DESCRIPTION
**Pull request by ascorbic**
Currently the plugin only supports sites where the gatsby root is in a subdirectory by setting the site base to the subdirectory. This means that the site root can't be the root of a monorepo. This PR changes that, so that the root is calculated relative to the publish dir (which is hard-coded in Gatsby), ensuring that all paths are still correct.

Fixes #271

### CODE REVIEW

File: plugin/src/templates/handlers.ts [hunk 1]
```diff
@@ -127,6 +134,32 @@ const getHandler = (renderMode: RenderMode, appDir: string): Handler => {
...
+    event: HandlerEvent,
+    context: HandlerContext,
+  ): Promise<HandlerResponse> {
+    // Create a fake Gatsby/Express Request object
+    const req = createRequestObject({ event, context })
+
+    return new Promise((resolve) => {
+      // Create a stubbed Gatsby/Express Response object
+      // onResEnd is the "resolve" cb for this Promise
+      const res = createResponseObject({ onResEnd: resolve })
```
Comment (ehmicky) [inline plugin/src/templates/handlers.ts:152]: Should this line be put inside the `try` block? Just in case it throws.

**Review by ehmicky — DISMISSED** [review]

**Review by ehmicky — APPROVED** [review]
